#!/usr/bin/env python3
"""
Generate Stan function signature database from stanc3 Generate.ml.

Assumes the stanc3 source directory is at ../
https://github.com/stan-dev/stanc3

Usage (from project root):
    python3 tools/generate_stan_signatures.py [path/to/stanc3/src]

Output: src/main/resources/stan_signatures.json
Re-run whenever stanc3 is updated.
"""

import re
import json
import sys
from itertools import product
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PROJECT_DIR = SCRIPT_DIR.parent
STANC3_SRC = (Path(sys.argv[1]) if len(sys.argv) > 1
              else PROJECT_DIR.parent / "stanc3" / "src")
GENERATE_ML = STANC3_SRC / "stan_math_signatures" / "Generate.ml"
OUTPUT_JSON = PROJECT_DIR / "src" / "main" / "resources" / "stan_signatures.json"

# ── Type string helpers ────────────────────────────────────────────────────────

def arr(t, depth=0):
    if depth == 0:
        return t
    return f"array[{','*(depth-1)}] {t}"

INT = "int"
REAL = "real"
COMPLEX = "complex"
VEC = "vector"
RVEC = "row_vector"
MAT = "matrix"
CVEC = "complex_vector"
CRVEC = "complex_row_vector"
CMAT = "complex_matrix"

TYPE_MAP = {
    "UInt": INT,
    "UReal": REAL,
    "UComplex": COMPLEX,
    "UVector": VEC,
    "URowVector": RVEC,
    "UMatrix": MAT,
    "UComplexVector": CVEC,
    "UComplexRowVector": CRVEC,
    "UComplexMatrix": CMAT,
}
FUN = "fun"  # placeholder type for UFun / UMathLibraryFunction (higher-order) args

BARE_TYPES     = [INT, REAL, COMPLEX, VEC, RVEC, MAT, CVEC, CRVEC, CMAT]
DEEP_BASE      = [INT, REAL, RVEC, VEC, MAT]
DEEP_COMPLEX_BASE = [COMPLEX, CVEC, CRVEC, CMAT]

def expand_array_sigs(sigs, name, base_types, depth_range, mk_args, mk_ret):
    """
    Replicate a Generate.ml ``List.iter (fun t -> List.iter (fun d -> ...))`` loop.

    For every (base_type, depth) pair, adds one signature entry:
        name( mk_args(base_type, depth) ) → mk_ret(base_type, depth)

    ``arr(t, 0)`` is the bare type ``t``; ``arr(t, d)`` for d > 0 is
    ``array[,…,] t`` with d-1 commas.  Use depth_range=range(0, N) to cover
    bare-type overloads (depth 0) alongside array overloads.
    """
    for bt in base_types:
        for d in depth_range:
            sigs.setdefault(name, set()).add((tuple(mk_args(bt, d)), mk_ret(bt, d)))

def expand_dim(d):
    if d == "DInt":       return [INT]
    if d == "DReal":      return [REAL]
    if d == "DVector":    return [VEC]
    if d == "DMatrix":    return [MAT]
    if d == "DIntArray":  return [arr(INT, 1)]
    if d == "DVInt":      return [INT, arr(INT, 1)]
    if d == "DVReal":     return [REAL, arr(REAL, 1), VEC, RVEC]
    if d == "DVComplex":  return [COMPLEX, arr(COMPLEX, 1), CVEC, CRVEC]
    if d == "DIntAndReals": return expand_dim("DVReal") + expand_dim("DVInt")
    if d == "DVectors":   return [VEC, arr(VEC, 1), RVEC, arr(RVEC, 1)]
    if d == "DComplexVectors": return [CVEC, arr(CVEC, 1), CRVEC, arr(CRVEC, 1)]
    if d == "DDeepVectorized":
        return [arr(b, depth) for b in DEEP_BASE for depth in range(8)]
    if d == "DDeepComplexVectorized":
        return [arr(b, depth) for b in DEEP_COMPLEX_BASE for depth in range(8)]
    return [d]

def _arr_parts(t):
    """Return (commas, inner_base) for an array[] type string."""
    bracket_end = t.index("]")
    return t[6:bracket_end], t[bracket_end + 2:]

def ints_to_real(t):
    if t == INT: return REAL
    if t.startswith("array["):
        commas, inner = _arr_parts(t)
        return f"array[{commas}] {ints_to_real(inner)}"
    return t

def complex_to_real(t):
    m = {COMPLEX: REAL, CVEC: VEC, CRVEC: RVEC, CMAT: MAT}
    if t in m: return m[t]
    if t.startswith("array["):
        commas, inner = _arr_parts(t)
        return f"array[{commas}] {complex_to_real(inner)}"
    return t

def real_to_complex(t):
    m = {REAL: COMPLEX, VEC: CVEC, RVEC: CRVEC, MAT: CMAT}
    if t in m: return m[t]
    if t.startswith("array["):
        commas, inner = _arr_parts(t)
        return f"array[{commas}] {real_to_complex(inner)}"
    return t

def is_primitive(t): return t in (INT, REAL)

def rng_return(rt, args):
    return rt if all(is_primitive(a) for a in args) else arr(rt, 1)

def all_combos(dims):
    return list(product(*[expand_dim(d) for d in dims]))

# Mirrors stanc3's missing_math_functions in src/stan_math_signatures/Generate.ml:
# functions that would be generated by the declarative expansion
# but don't actually exist in Stan math.
MISSING = {"beta_proportion_cdf", "loglogistic_lcdf"}

FULL_LPDF = ["Lpdf", "Rng", "Ccdf", "Cdf"]
FULL_LPMF = ["Lpmf", "Rng", "Ccdf", "Cdf"]

def fkind_suffixes(fk):
    return {"Lpmf": ["_lpmf"], "Lpdf": ["_lpdf"], "Rng": ["_rng"],
            "Cdf": ["_cdf", "_lcdf"], "Ccdf": ["_lccdf"]}.get(fk, [""])

# ── Declarative signature generators ──────────────────────────────────────────

def process_dist(fkinds, name, dims):
    out = []
    for fk in fkinds:
        if fk == "Rng":
            rt_dim, arg_dims = dims[0], dims[1:]
            promoted_rt = INT if rt_dim in ("DInt", "DIntArray", "DVInt") else REAL
            edims = ["DIntAndReals" if d == "DVReal" else d for d in arg_dims]
            for args in all_combos(edims):
                fn = name + "_rng"
                if fn not in MISSING:
                    out.append((fn, list(args), rng_return(promoted_rt, args)))
        else:
            for suffix in fkind_suffixes(fk):
                fn = name + suffix
                if fn not in MISSING:
                    for args in all_combos(dims):
                        out.append((fn, list(args), REAL))
    return out

def process_math(fkinds, name, dims):
    out = []
    for fk in fkinds:
        behavior = fk.replace("UnaryVectorized ", "")
        for args in all_combos(dims):
            first = args[0]
            if   behavior == "SameAsArg":      rt = first
            elif behavior == "IntsToReals":    rt = ints_to_real(first)
            elif behavior == "ComplexToReals": rt = complex_to_real(first)
            else:                              rt = REAL
            out.append((name, list(args), rt))
    return out

# ── Generate.ml parser ────────────────────────────────────────────────────────

def parse_utype(s):
    s = s.strip()
    # bare_array_type (UType, N) — literal numeric depth, e.g. bare_array_type (UReal, 2)
    m = re.match(r'bare_array_type\s*\(\s*(U\w+)\s*,\s*(\d+)\s*\)$', s)
    if m:
        base = TYPE_MAP.get(m.group(1))
        return arr(base, int(m.group(2))) if base else None
    depth = 0
    while s.startswith("UArray"):
        depth += 1
        s = s[6:].strip()
    base = TYPE_MAP.get(s)
    return None if base is None else arr(base, depth)

def parse_ret_value(raw_ret):
    """Parse a captured return-type string to a type value, or None to skip.

    Returns:
      "void"          – for Void
      a type string   – for ordinary types
      a list of strs  – for UTuple [T1; T2; ...] returns (→ JSON array)
      None            – if the type cannot be represented
    """
    if raw_ret is None:
        return "void"
    s = raw_ret.strip()
    if s.startswith('(') and s.endswith(')'):
        s = s[1:-1].strip()
    m = re.match(r'UTuple\s*\[([^\]]*)\]$', s)
    if m:
        parts = [p.strip() for p in m.group(1).split(';') if p.strip()]
        types = [parse_utype(p) for p in parts]
        return None if any(t is None for t in types) else types
    return parse_utype(s)


def parse_arg_list(s):
    parts = [p.strip() for p in re.split(r';', s) if p.strip()]
    result = []
    for p in parts:
        if any(kw in p for kw in ("UFun", "UMathLibraryFunction")):
            result.append(FUN)
            continue
        # Strip (DataOnly, ...) / (AutoDiffable, ...) qualifier wrappers used by add_qualified.
        qualified = re.match(r'\(\s*(?:DataOnly|AutoDiffable)\s*,\s*(.+)\s*\)$', p)
        if qualified:
            p = qualified.group(1).strip()
        t = parse_utype(p)
        if t is None: return None
        result.append(t)
    return result

def parse_distributions(text):
    m = re.search(r'let distributions\s*=\s*\[(.*?)\](?=\s*\n\s*let\s)', text, re.DOTALL)
    if not m: return []
    block = m.group(1)
    out = []
    for em in re.finditer(r'\(\s*((?:full_lpdf|full_lpmf|\[[^\]]*\]))\s*,\s*"([^"]+)"\s*,\s*\[([^\]]*)\]', block, re.DOTALL):
        raw_fkinds, name, raw_dims = em.group(1).strip(), em.group(2), em.group(3)
        if   raw_fkinds == "full_lpdf": fkinds = FULL_LPDF
        elif raw_fkinds == "full_lpmf": fkinds = FULL_LPMF
        else: fkinds = re.findall(r'(?:Lpmf|Lpdf|Rng|Cdf|Ccdf)', raw_fkinds)
        dims = re.findall(r'D\w+', raw_dims)
        if dims: out.extend(process_dist(fkinds, name, dims))
    return out

def parse_math_sigs(text):
    m = re.search(r'let math_sigs\s*=\s*\[(.*?)\](?=\s*\n\s*let\s)', text, re.DOTALL)
    if not m: return []
    block = m.group(1)
    out = []
    for em in re.finditer(r'\(\s*\[([^\]]*)\]\s*,\s*"([^"]+)"\s*,\s*\[([^\]]*)\]', block, re.DOTALL):
        raw_fkinds, name, raw_dims = em.group(1).strip(), em.group(2), em.group(3)
        if   "SameAsArg"    in raw_fkinds: fkinds = ["UnaryVectorized SameAsArg"]
        elif "ComplexToReals" in raw_fkinds: fkinds = ["UnaryVectorized ComplexToReals"]
        else:                              fkinds = ["UnaryVectorized IntsToReals"]
        dims = re.findall(r'D\w+', raw_dims)
        if dims: out.extend(process_math(fkinds, name, dims))
    return out

def parse_explicit(text, sigs):
    """Parse add_unqualified and helper calls from the imperative section."""

    def add(name, args, ret):
        if name not in sigs: sigs[name] = set()
        # Lists (UTuple returns) are unhashable; store as tuple, serialise back later.
        ret_key = tuple(ret) if isinstance(ret, list) else ret
        sigs[name].add((tuple(args), ret_key))

    # Return-type pattern shared by add_unqualified and add_qualified.
    # Group 1 captures the type expression:
    #   • "(UTuple [T1; T2; ...])" or "UTuple [...]"  → tuple return (JSON array)
    #   • "(UArray UInt)" / "UMatrix" / etc.          → plain type
    #   • Void                                         → group 1 is None
    RET_PAT = (r'(?:ReturnType\s+'
               r'(\(?UTuple\s*\[[^\]]*\]\)?|\(?U\w+(?:\s+U\w+)*\)?)'
               r'|Void)')

    # add_unqualified("name", ReturnType ..., [...], mem)
    # Args list uses [^\]]* which works because simple-type args have no nested brackets.
    # UFun-args functions are captured but parse_arg_list maps UFun → "fun".
    for m in re.finditer(
        r'add_unqualified\s*\(\s*"([^"]+)"\s*,\s*' + RET_PAT +
        r'\s*,\s*\[([^\]]*)\]\s*,\s*(?:SoA|AoS)\s*\)',
        text, re.DOTALL
    ):
        name = m.group(1)
        raw_ret = m.group(2)
        raw_args = m.group(3)
        ret = parse_ret_value(raw_ret)
        if ret is None: continue
        args = parse_arg_list(raw_args)
        if args is None: continue
        add(name, args, ret)

    # add_qualified("name", ReturnType ..., [(DataOnly, UType); ...], mem)
    # Same as add_unqualified but args carry a DataOnly/AutoDiffable qualifier;
    # parse_arg_list strips those qualifiers so types are extracted normally.
    # UFun-args functions: the [^\]]* stops at the first ] inside UFun's arg list,
    # so parse_arg_list sees a partial string; any UFun token maps to "fun".
    # Functions with deeply nested args that can't be parsed here are hard-coded below.
    for m in re.finditer(
        r'add_qualified\s*\(\s*"([^"]+)"\s*,\s*' + RET_PAT +
        r'\s*,\s*\[([^\]]*)\]\s*,\s*(?:SoA|AoS)\s*\)',
        text, re.DOTALL
    ):
        name = m.group(1)
        raw_ret = m.group(2)
        raw_args = m.group(3)
        ret = parse_ret_value(raw_ret)
        if ret is None: continue
        args = parse_arg_list(raw_args)
        if args is None: continue
        add(name, args, ret)

    # add_binary_vec "name" mem  → scalars+vectors, ints_to_real return
    for m in re.finditer(r'add_binary_vec\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        scalars  = [INT, REAL]
        vectors  = [VEC, RVEC, MAT, arr(INT, 1), arr(REAL, 1)]
        for s in scalars:
            for t in scalars: add(name, [s, t], ints_to_real(s))
        for v in vectors:
            add(name, [v, v], ints_to_real(v))
            for s in scalars:
                add(name, [v, s], ints_to_real(v))
                add(name, [s, v], ints_to_real(v))

    # add_binary_vec_real_real "name" mem
    for m in re.finditer(r'add_binary_vec_real_real\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        for t in [REAL, VEC, RVEC, MAT, arr(REAL, 1)]:
            add(name, [t, t], t)
            if t != REAL:
                add(name, [t, REAL], t)
                add(name, [REAL, t], t)

    # add_binary_vec_complex_complex "name" mem
    for m in re.finditer(r'add_binary_vec_complex_complex\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        for t in [COMPLEX, CVEC, CRVEC, CMAT, arr(COMPLEX, 1)]:
            add(name, [t, t], t)
            if t != COMPLEX:
                add(name, [t, COMPLEX], t)
                add(name, [COMPLEX, t], t)

    # add_binary_vec_int_real "name" mem
    for m in re.finditer(r'add_binary_vec_int_real\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        for t in [VEC, RVEC, MAT, arr(REAL, 1)]:
            for d in range(8):
                add(name, [INT, arr(t if d == 0 else REAL, d)], arr(t if d == 0 else REAL, d))

    # add_binary_vec_real_int "name" mem
    for m in re.finditer(r'add_binary_vec_real_int\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        for t in [VEC, RVEC, MAT, arr(REAL, 1)]:
            add(name, [t, INT], t)

    # add_binary_vec_int_int "name" mem
    for m in re.finditer(r'add_binary_vec_int_int\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        for d in range(8):
            t = arr(INT, d)
            add(name, [t, INT], t)
            if d > 0: add(name, [INT, t], t)
            if d > 0: add(name, [t, t], t)

    # add_first_arg_vector_binary "name" mem
    for m in re.finditer(r'add_first_arg_vector_binary\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        add(name, [REAL, REAL], REAL)
        for t in [VEC, RVEC, MAT, arr(REAL, 1)]:
            for d in range(8):
                ty = arr(t if d == 0 else REAL, d) if d > 0 else t
                add(name, [ty, ty], ty)
                add(name, [ty, REAL], ty)

    # add_first_arg_vector_ternary "name" mem
    for m in re.finditer(r'add_first_arg_vector_ternary\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        add(name, [REAL, REAL, REAL], REAL)
        for t in [VEC, RVEC, MAT, arr(REAL, 1)]:
            add(name, [t, t, t], t); add(name, [t, t, REAL], t)
            add(name, [t, REAL, t], t); add(name, [t, REAL, REAL], t)

    # add_ternary_vec "name" mem
    for m in re.finditer(r'add_ternary_vec\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        name = m.group(1)
        add(name, [REAL, REAL, REAL], REAL)
        for t in [VEC, RVEC, MAT]:
            for a in [t, REAL]:
                for b in [t, REAL]:
                    add(name, [t, a, b], t)
                    add(name, [REAL, t, b] if b != REAL else [REAL, t, b], t)
                    add(name, [REAL, a, t] if a != REAL else [REAL, a, t], t)

    # add_nested_unary UType "name" mem
    for m in re.finditer(r'add_nested_unary\s+(\w+)\s+"([^"]+)"\s+(?:SoA|AoS)', text):
        base_raw, name = m.group(1), m.group(2)
        base = TYPE_MAP.get(base_raw)
        if base:
            for d in range(8):
                t = arr(base, d)
                add(name, [t], t)

    # add_nullary "name"
    for m in re.finditer(r'add_nullary\s+"([^"]+)"', text):
        add(m.group(1), [], REAL)

    # for_all_vector_types / for_vector_types patterns — skip (complex expansion)

def main():
    print(f"Reading {GENERATE_ML} ...")
    text = GENERATE_ML.read_text(encoding="utf-8")

    # Collect into dict: name → set of (args_tuple, ret)
    sigs: dict[str, set] = {}

    def add_list(entries):
        for name, args, ret in entries:
            if name not in sigs: sigs[name] = set()
            ret_key = tuple(ret) if isinstance(ret, list) else ret
            sigs[name].add((tuple(args), ret_key))

    print("Processing distributions ...")
    add_list(parse_distributions(text))

    print("Processing math signatures ...")
    add_list(parse_math_sigs(text))

    print("Processing explicit add_* calls ...")
    parse_explicit(text, sigs)

    # ── Loop-expansion entries (Generate.ml List.iter patterns) ───────────────
    #
    # Generate.ml's imperative section uses OCaml List.iter loops to expand
    # batches of add_unqualified / add_qualified calls over type × depth
    # combinations.  The regex parsers above only handle static call sites;
    # these loops are replicated via expand_array_sigs().
    #
    # Functions still absent and why:
    #   cholesky_factor_corr/cov/corr_matrix/cov_matrix/stochastic_*
    #                      _constrain/jacobian/unconstrain
    #     → internal constraint-transform helpers; not user-callable.
    #   beta_proportion_rng (vector overloads), hypergeometric_3F2/pFq,
    #   log_mix (vector overloads)
    #     → iterate over vector_types or use for_all_vector_types helper
    #       (not bare_types); scalar overloads come from the dist expander.

    B = BARE_TYPES  # shorthand; same list as the module-level constant

    # head, tail — (List.range 1 4) × bare_types: f(array[d] T, int) → array[d] T
    # segment    — same loop: f(array[d] T, int, int) → array[d] T
    expand_array_sigs(sigs, "head",    B, range(1, 4),
        lambda bt, d: [arr(bt, d), INT],      lambda bt, d: arr(bt, d))
    expand_array_sigs(sigs, "tail",    B, range(1, 4),
        lambda bt, d: [arr(bt, d), INT],      lambda bt, d: arr(bt, d))
    expand_array_sigs(sigs, "segment", B, range(1, 4),
        lambda bt, d: [arr(bt, d), INT, INT], lambda bt, d: arr(bt, d))

    # reverse — (List.range 1 8) × bare_types: f(array[d] T) → array[d] T
    expand_array_sigs(sigs, "reverse", B, range(1, 8),
        lambda bt, d: [arr(bt, d)], lambda bt, d: arr(bt, d))

    # size — two loops unified via depth 0 = bare type:
    #   (List.range 1 8) × bare_types  +  bare_types alone (depth 0)
    expand_array_sigs(sigs, "size", B, range(0, 8),
        lambda bt, d: [arr(bt, d)], lambda bt, d: INT)

    # to_int — add_qualified (List.range 0 8) × [UReal; UInt]
    # DataOnly qualifier dropped (not enforced in the DB).
    expand_array_sigs(sigs, "to_int", [REAL, INT], range(0, 8),
        lambda bt, d: [arr(bt, d)], lambda bt, d: arr(INT, d))

    # append_array — (List.range 1 8) × bare_types:
    #   f(array[d] T, array[d] T) → array[d] T
    expand_array_sigs(sigs, "append_array", B, range(1, 8),
        lambda bt, d: [arr(bt, d), arr(bt, d)], lambda bt, d: arr(bt, d))

    # rep_array — loop over bare_types producing three depth-shift patterns:
    #   shift +1: depth 0–7  rep_array(array[d] T, int)        → array[d+1] T
    #   shift +2: depth 0–6  rep_array(array[d] T, int, int)   → array[d+2] T
    #   shift +3: depth 0    rep_array(T, int, int, int)        → array[3] T
    expand_array_sigs(sigs, "rep_array", B, range(0, 8),
        lambda bt, d: [arr(bt, d), INT],           lambda bt, d: arr(bt, d + 1))
    expand_array_sigs(sigs, "rep_array", B, range(0, 7),
        lambda bt, d: [arr(bt, d), INT, INT],      lambda bt, d: arr(bt, d + 2))
    expand_array_sigs(sigs, "rep_array", B, range(0, 1),
        lambda bt, d: [arr(bt, d), INT, INT, INT], lambda bt, d: arr(bt, d + 3))

    # to_array_2d — two literal add_unqualified calls whose return type uses
    # `bare_array_type (UReal, 2)` syntax (nested parens, non-U… identifier),
    # which the regex cannot capture.
    sigs.setdefault("to_array_2d", set()).add((tuple([MAT]),  arr(REAL,    2)))
    sigs.setdefault("to_array_2d", set()).add((tuple([CMAT]), arr(COMPLEX, 2)))

    # ── Hard-coded: UFun (higher-order function arg) signatures ───────────────
    #
    # These functions have nested bracket structure in their arg lists that the
    # [^\]]* regex cannot parse.  The function-valued argument is represented as
    # the placeholder type "fun"; callers skip type-checking for "fun" params.
    #
    # Source: stanc3 src/stan_math_signatures/Generate.ml add_qualified calls.

    def _add(name, args, ret):
        ret_key = tuple(ret) if isinstance(ret, list) else ret
        sigs.setdefault(name, set()).add((tuple(args), ret_key))

    _ODE_ARGS_BASE = [FUN, arr(REAL, 1), REAL,
                      arr(REAL, 1), arr(REAL, 1), arr(REAL, 1), arr(INT, 1)]
    _ODE_RET = arr(REAL, 2)  # array[,] real  (= UArray (UArray UReal))

    for _ode in ("integrate_ode", "integrate_ode_adams",
                 "integrate_ode_bdf", "integrate_ode_rk45"):
        _add(_ode, _ODE_ARGS_BASE, _ODE_RET)
        _add(_ode, _ODE_ARGS_BASE + [REAL, REAL, REAL], _ODE_RET)  # tolerance overload

    _add("integrate_1d",
         [FUN, REAL, REAL, arr(REAL, 1), arr(REAL, 1), arr(INT, 1)], REAL)
    _add("integrate_1d",
         [FUN, REAL, REAL, arr(REAL, 1), arr(REAL, 1), arr(INT, 1), REAL], REAL)

    for _alg in ("algebra_solver", "algebra_solver_newton"):
        _add(_alg, [FUN, VEC, VEC, arr(REAL, 1), arr(INT, 1)], VEC)
        _add(_alg, [FUN, VEC, VEC, arr(REAL, 1), arr(INT, 1), REAL, REAL, REAL], VEC)

    _add("map_rect",
         [FUN, VEC, arr(VEC, 1), arr(REAL, 2), arr(INT, 2)], VEC)

    # ── Hard-coded: generate_laplace_options (List.iter loop, UTuple return) ──
    _LAPLACE_TUPLE = [VEC, REAL, INT, INT, INT, INT]
    for _t in (INT, VEC):
        _add("generate_laplace_options", [_t], _LAPLACE_TUPLE)

    # ── Serialise: name → list of [args_list, ret] ────────────────────────────
    # ret is a string (plain type or "void") or a list of strings (UTuple).
    # Within a function's overloads, tuple rets are stored as Python tuples for
    # hashability; convert back to lists for JSON output.

    def _ret_for_json(ret_key):
        return list(ret_key) if isinstance(ret_key, tuple) else ret_key

    def _sig_sort_key(entry):
        args, ret = entry
        # Sort: string rets before tuple rets; within each group, natural order.
        return (args, 0 if isinstance(ret, str) else 1, ret)

    out = {name: [[list(args), _ret_for_json(ret)] for args, ret in sorted(entries, key=_sig_sort_key)]
           for name, entries in sorted(sigs.items())}

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps({"v": 2, "f": out}, separators=(",", ":")))

    total = sum(len(v) for v in out.values())
    print(f"Wrote {total} signatures for {len(out)} functions → {OUTPUT_JSON}")

if __name__ == "__main__":
    main()
